// DEFINING YOUR OWN TYPES IN C.

// USING TYPEDEF WE HAVE DEFINED Counter TYPE NOW WE CAN USE IT TO DEFINE OUR VARIABLES.
// TYPEDEF ISN’T USED PARTICULARLY OFTEN IN MOST BASIC C CODE, BUT YOU MAY COME ACROSS IT IN APPLICATIONS REQUIRING A HIGH DEGREE OF PORTABILITY.
// ONE PLACE YOU MAY SEE TYPEDEF USED MORE OFTEN IS WHILE SIMPLIFYING THE DECLARATION OF COMPOUND TYPES SUCH AS THE STRUCT TYPE

int main()
{
    typedef int Counter;
    Counter i, j, k;

    return 0;
}